fail_on_severity: 'low'
allow_licenses:
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'BSD-3-Clause-Clear'
  - 'MIT'
  - 'Apache-2.0'
  - 'ISC'
  - 'BlueOak-1.0.0'
  - '0BSD'
  - 'Python-2.0'
  - 'Zlib'
  - 'MPL-2.0'
  - 'MIT-CMU'
fail-on-scopes:
  - 'runtime'
license-check: true
vulnerability-check: true