fail_on_severity: 'low'
allow_licenses:
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'MIT'
  - 'Apache-2.0'
  - 'ISC'
  - 'BlueOak-1.0.0'
  - '0BSD'
  - 'Python-2.0'
  - 'Zlib'
  - 'MPL-2.0'
  - 'MIT-CMU'
  - 'ISC'
fail_on_scopes:
  - 'runtime'
license_check: true
vulnerability_check: true
comment_summary_in_pr: true
