name: Install uv
description: Install uv on Linux, macOS, and Windows
runs:
  using: "composite"
  steps:
    - name: Install uv (Linux/macOS)
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/0.6.17/install.sh | sh
        # shell autocompletion
        echo 'eval "$(uv generate-shell-completion bash)"' >> ~/.bashrc
        echo 'eval "$(uvx --generate-shell-completion bash)"' >> ~/.bashrc
      
    - name: Install uv (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/0.6.17/install.ps1 | iex"
        if (!(Test-Path -Path $PROFILE)) {
          New-Item -ItemType File -Path $PROFILE -Force
        }
        Add-Content -Path $PROFILE -Value '(& uv generate-shell-completion powershell) | Out-String | Invoke-Expression'
        Add-Content -Path $PROFILE -Value '(& uv generate-shell-completion powershell) | Out-String | Invoke-Expression'
      
    - name: Configure uv
      shell: bash
      run: |
        uv --version
