name: "Pull Request Labeler"
on:
  pull_request_target:

env:
  LABELER_CONFIG: '.github/labeler.yml'

permissions: read-all

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Clone Labeler configuration
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        sparse-checkout: ${{ env.LABELER_CONFIG }}

    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ${{ env.LABELER_CONFIG }}
        sync-labels: 'true'
